server:
  port: 8000
  error:
    include-message: always
    include-binding-errors: always

spring:
  main:
    banner_mode: CONSOLE

  datasource:
    platform: org.hibernate.dialect.MySQL5Dialect
    url: jdbc:mysql://127.0.0.1:3306/arb_schedule_db?useUnicode=yes&characterEncoding=UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    initialize: true
    initialization-mode: always
    continue-on-error: true
    data: classpath:sql/arb_schedule_db_init_data.sql

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      show_sql: false
      use_sql_comments: true
      format_sql: true
      type: trace
#      generate-ddl: true
      ddl-auto: update # update/create
      cache:
        use_second_level_cache: true
        use_query_cache: true
        region:
          factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
    javax:
      persistence:
        sharedCache:
          mode: ALL

hibernate:
  globally_quoted_identifiers: true

com:
  user:
    arb:
      maxScheduleInterval: 100